//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : BaseEntity
    {
        public string name { get; set; }
        public int salary { get; set; }
        public long idDepartment { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
